<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit093da2bb77731833c660c03a9d0af63e
{
    public static $prefixLengthsPsr4 = array (
        'T' => 
        array (
            'Tests\\' => 6,
        ),
        'P' => 
        array (
            'Psr\\Log\\' => 8,
        ),
        'M' => 
        array (
            'Monolog\\' => 8,
        ),
        'A' => 
        array (
            'App\\' => 4,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Tests\\' => 
        array (
            0 => __DIR__ . '/../..' . '/tests',
        ),
        'Psr\\Log\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/log/src',
        ),
        'Monolog\\' => 
        array (
            0 => __DIR__ . '/..' . '/monolog/monolog/src/Monolog',
        ),
        'App\\' => 
        array (
            0 => __DIR__ . '/../..' . '/app',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit093da2bb77731833c660c03a9d0af63e::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit093da2bb77731833c660c03a9d0af63e::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit093da2bb77731833c660c03a9d0af63e::$classMap;

        }, null, ClassLoader::class);
    }
}
